import os
import json
import logging
from typing import Dict, Any
import datetime

from openai import OpenAI
import config

logger = logging.getLogger(__name__)

# Initialize OpenAI client with generic Base URL for Deepseek/Other compatibility
try:
    client = OpenAI(
        api_key=config.LLM_API_KEY,
        base_url=config.LLM_BASE_URL
    )
except Exception as e:
    client = None
    logger.error(f"Failed to initialize LLM client: {e}")

def _get_live_news_context(symbol: str = "") -> str:
    """Fetches high-impact macro alerts from local cache and falls back/enhances with yfinance."""
    context_lines = []
    
    cache_file = "ingestion/news_cache.json"
    if os.path.exists(cache_file):
        try:
            with open(cache_file, "r") as f:
                cache_data = json.load(f)
            alerts = [a for a in cache_data.values() if a.get("macro_impact") == "HIGH" or a.get("political_figure")]
            sorted_alerts = sorted(alerts, key=lambda x: x.get("ts", ""), reverse=True)[:5]
            if sorted_alerts:
                context_lines.append("=== HIGH-IMPACT MACRO/POLITICAL ALERTS (MUST CONSIDER FOR RIPPLE EFFECTS) ===")
                for a in sorted_alerts:
                    context_lines.append(f"- [{a.get('sentiment', 'neutral').upper()}] {a.get('title', '')}")
        except Exception as e:
            logger.warning(f"Failed to read news cache: {e}")

    ticker_query = f"{symbol}.NS" if symbol else "^NSEI"
    try:
        import yfinance as yf
        logger.info(f"AI Chat scraping yfinance for {ticker_query}")
        results = yf.Ticker(ticker_query).news
        if results:
            context_lines.append(f"=== RECENT LIVE HEADLINES ({ticker_query}) ===")
            news_snippets = [f"- {r.get('title', '')}: {r.get('summary', '')}" for r in results[:4]]
            context_lines.extend(news_snippets)
    except Exception as e:
        logger.warning(f"Yahoo news search failed: {e}")

    if not context_lines:
        return "No live web data attached."
    
    return "\n".join(context_lines)

def get_market_query_response(query: str, history: list = None) -> str:
    """Answers a general market trading question."""
    if not client:
        return "Error: LLM client not configured. Please check your .env file."
    
    # Fetch hybrid live web and macro context based on user's query
    live_news_context = _get_live_news_context("")

    messages = [
        {"role": "system", "content": f"""You are the Head Quant and Chief Market Analyst of an elite algorithmic trading firm. 
You must never be vague. You must give specific, actionable, and data-backed analysis.
When discussing the market, reference real-world events, inflation data, or technical setups.
If the user asks an open-ended question like "Market", analyze the following real-time web news and summarize the current market sentiment violently and clinically.
CRITICAL: Speculate aggressively on any macroeconomic or political "ripples" seen in the alerts.

CURRENT DATE AND TIME: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
Assume this as your current operating date. Do not mention your data cutoff date.

[LIVE REAL-TIME WEB CONTEXT]:
{live_news_context}
"""}
    ]
    if history:
        messages.extend(history)
    messages.append({"role": "user", "content": query})

    try:
        response = client.chat.completions.create(
            model=config.LLM_MODEL,
            messages=messages,
            max_tokens=1200,
            temperature=0.4
        )
        return response.choices[0].message.content
    except Exception as e:
        logger.error(f"AI Market Query Error: {e}")
        return f"Error communicating with AI: {str(e)}"

def evaluate_signal(signal_data: Dict[str, Any]) -> Dict[str, Any]:
    """
    Passes a trading signal through the AI committee.
    Returns the discussion log and a final Approved/Rejected status.
    """
    if not client:
        return {"error": "LLM client not configured."}

    # Fetch hybrid live web and macro context
    symbol = signal_data.get("symbol", "")
    live_news_context = _get_live_news_context(symbol)

    # Format the signal into a string representation
    signal_prompt = json.dumps(signal_data, indent=2)

    system_prompt = f"""
You are the Head Quant of a major proprietary trading firm.
You are given a potential trading signal generated by automated algorithms.
Your job is to simulate a quick discussion among three personas:
1. Technical Analyst: Evaluates the chart setup, RSI, MACD, Patterns and Breakouts.
2. Risk Manager: Evaluates the Risk-Reward ratio, Stop Loss placement, and Capital Risk. Adjusts risk dynamically for any macro black-swan events.
3. Head Quant: Listens to the other two, reviews real-time web news and MACRO/POLITICAL ALERTS, to actively speculate on geopolitical ripples and makes a final decision.

CURRENT DATE AND TIME: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
Assume this as your current operating date. Do not mention your data cutoff date.

Output ONLY a JSON object with the following structure. Do not wrap it in markdown code blocks, just raw JSON:
{{
  "technical_analyst_opinion": "string",
  "risk_manager_opinion": "string",
  "head_quant_summary": "string",
  "final_decision": "APPROVED" | "REJECTED"
}}

[LIVE WEB SEARCH RESULTS] (Analyze this for immediate red/green flags!):
{live_news_context}

Signal Data:
{signal_prompt}
    """

    try:
        response = client.chat.completions.create(
            model=config.LLM_MODEL,
            messages=[
                {"role": "system", "content": "You are an AI committee that outputs raw JSON only. No markdown, no code blocks. Just the JSON object."},
                {"role": "user", "content": system_prompt}
            ],
            temperature=0.2,
            max_tokens=900
        )

        result_content = response.choices[0].message.content.strip()

        # Strip any accidental markdown code fences Groq might add
        if result_content.startswith("```"):
            import re
            match = re.search(r'\{.*\}', result_content, re.DOTALL)
            result_content = match.group(0) if match else result_content

        result_json = json.loads(result_content)
        return result_json

    except json.JSONDecodeError as e:
        logger.error(f"AI JSON Decode Error: {e} | Raw: {result_content[:200]}")
        return {"error": "AI returned invalid JSON", "raw": result_content[:500]}
    except Exception as e:
        logger.error(f"AI Evaluation Error: {e}")
        return {"error": str(e)}


def debate_query(query: str) -> Dict[str, Any]:
    """
    Runs a free-form user query through all 3 personas as a live debate.
    Returns structured JSON so the UI can render each persona separately.
    """
    if not client:
        return {"error": "LLM client not configured."}

    # Fetch hybrid live market context
    live_news_context = _get_live_news_context("")

    system_prompt = f"""You are simulating a real-time debate inside an elite proprietary trading firm's war room.
The user has asked a market question. Three expert personas must each give their sharp, specific, data-driven opinion.

CURRENT DATE AND TIME: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
Assume this as your current operating date. Do not mention your data cutoff date.

You have access to the following LIVE real-time market news context. Reference it directly in your responses.

[LIVE REAL-TIME MARKET NEWS]:
{live_news_context}

USER QUERY: "{query}"

Respond ONLY with a raw JSON object (no markdown, no code fences):
{{
  "technical_analyst": {{
    "name": "Alex Chen — Technical Analyst",
    "opinion": "2-3 sentence sharp technical analysis referencing specific levels, indicators, and chart patterns. Be very specific with numbers."
  }},
  "risk_manager": {{
    "name": "Priya Kapoor — Risk Manager",
    "opinion": "2-3 sentence risk assessment referencing position sizing, stop-loss levels, R:R ratio, and capital exposure. Aggressively consider macroeconomic and political ripples! Be direct about what could blow up."
  }},
  "head_quant": {{
    "name": "Marcus Reid — Head Quant",
    "opinion": "2-3 sentence final verdict synthesizing both views and referencing the live news/macro context. Speculate heavily on geopolitical ripples. State clearly: TRADE or NO TRADE and why.",
    "verdict": "TRADE" or "NO TRADE"
  }}
}}"""

    try:
        response = client.chat.completions.create(
            model=config.LLM_MODEL,
            messages=[
                {"role": "system", "content": "You are a trading firm AI committee. Output only raw JSON, no markdown."},
                {"role": "user", "content": system_prompt}
            ],
            temperature=0.5,
            max_tokens=1000
        )

        result_content = response.choices[0].message.content.strip()

        # Strip markdown code fences if Groq wraps the response
        if result_content.startswith("```"):
            import re
            match = re.search(r'\{.*\}', result_content, re.DOTALL)
            result_content = match.group(0) if match else result_content

        result_json = json.loads(result_content)
        result_json["type"] = "debate"
        return result_json

    except json.JSONDecodeError as e:
        logger.error(f"Debate JSON error: {e} | Raw: {result_content[:200]}")
        return {"error": "AI returned invalid JSON", "raw": result_content[:500]}
    except Exception as e:
        logger.error(f"Debate error: {e}")
        return {"error": str(e)}
